import { motion } from 'framer-motion';
import { FaLink, FaRobot, FaChartLine, FaLock, FaLightbulb, FaMobileAlt } from 'react-icons/fa';
import { Link } from 'react-router-dom';
const AboutPage = () => {
  const features = [
    {
      icon: <FaLink className="text-4xl text-indigo-600" />,
      title: "One-Click Saving",
      description: "Save any web link instantly with a single click. Organize them with custom tags for easy retrieval."
    },
    {
      icon: <FaRobot className="text-4xl text-indigo-600" />,
      title: "AI-Powered Summaries",
      description: "Get concise, meaningful summaries of your saved content automatically generated by our advanced AI."
    },
    {
      icon: <FaChartLine className="text-4xl text-indigo-600" />,
      title: "Productivity Analytics",
      description: "Track your reading habits and time spent on saved content with insightful visual analytics."
    },
    {
      icon: <FaLock className="text-4xl text-indigo-600" />,
      title: "Secure Storage",
      description: "Your links and data are encrypted and protected with enterprise-grade security protocols."
    },
    {
      icon: <FaLightbulb className="text-4xl text-indigo-600" />,
      title: "Smart Recommendations",
      description: "Receive personalized content suggestions based on your saved links and reading patterns."
    },
    {
      icon: <FaMobileAlt className="text-4xl text-indigo-600" />,
      title: "Cross-Platform Access",
      description: "Access your saved links and summaries from any device, anywhere, anytime."
    }
  ];

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.2
      }
    }
  };

  const itemVariants = {
    hidden: { y: 20, opacity: 0 },
    visible: {
      y: 0,
      opacity: 1,
      transition: {
        duration: 0.5
      }
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-b from-gray-50 to-indigo-50 py-12 px-4 sm:px-6 lg:px-8">
      {/* Hero Section */}
      <motion.section 
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.8 }}
        className="max-w-7xl mx-auto text-center mb-16"
      >
        <h1 className="text-4xl md:text-6xl font-bold text-gray-900 mb-6">
          <span className="bg-clip-text text-transparent bg-gradient-to-r from-indigo-600 to-purple-600">
            About LinkSaver + AutoSummarizer
          </span>
        </h1>
        <p className="text-xl text-gray-600 max-w-3xl mx-auto">
          Revolutionizing how you save, organize, and consume web content with powerful AI technology.
        </p>
      </motion.section>

      {/* Mission Statement */}
      <motion.div 
        initial={{ opacity: 0 }}
        whileInView={{ opacity: 1 }}
        viewport={{ once: true }}
        transition={{ duration: 0.8, delay: 0.2 }}
        className="max-w-7xl mx-auto bg-white rounded-2xl shadow-xl p-8 mb-16"
      >
        <div className="text-center">
          <h2 className="text-3xl font-bold text-gray-900 mb-6">Our Mission</h2>
          <p className="text-lg text-gray-600 max-w-4xl mx-auto">
            To empower digital productivity by transforming information overload into organized knowledge. We combine 
            intuitive link management with AI-powered summarization to help you focus on what matters most.
          </p>
        </div>
      </motion.div>

      {/* Features Grid */}
      <motion.section
        variants={containerVariants}
        initial="hidden"
        whileInView="visible"
        viewport={{ once: true }}
        className="max-w-7xl mx-auto mb-16"
      >
        <h2 className="text-3xl font-bold text-center text-gray-900 mb-12">Key Benefits</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {features.map((feature, index) => (
            <motion.div
              key={index}
              variants={itemVariants}
              whileHover={{ y: -5 }}
              className="bg-white p-8 rounded-xl shadow-lg hover:shadow-xl transition-shadow duration-300"
            >
              <div className="text-center mb-6">
                {feature.icon}
              </div>
              <h3 className="text-xl font-bold text-center text-gray-900 mb-3">{feature.title}</h3>
              <p className="text-gray-600 text-center">{feature.description}</p>
            </motion.div>
          ))}
        </div>
      </motion.section>

      {/* How It Works */}
      <motion.section 
        initial={{ opacity: 0 }}
        whileInView={{ opacity: 1 }}
        viewport={{ once: true }}
        transition={{ duration: 0.8 }}
        className="max-w-7xl mx-auto bg-indigo-600 rounded-2xl shadow-xl p-8 mb-16 text-white"
      >
        <h2 className="text-3xl font-bold text-center mb-8">How It Works</h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          <div className="text-center">
            <div className="bg-white text-indigo-600 w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold">1</div>
            <h3 className="text-xl font-bold mb-3">Save</h3>
            <p>Add any web link with optional tags for organization</p>
          </div>
          <div className="text-center">
            <div className="bg-white text-indigo-600 w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold">2</div>
            <h3 className="text-xl font-bold mb-3">Summarize</h3>
            <p>Our AI processes the content and generates a concise summary</p>
          </div>
          <div className="text-center">
            <div className="bg-white text-indigo-600 w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4 text-2xl font-bold">3</div>
            <h3 className="text-xl font-bold mb-3">Organize</h3>
            <p>Access your knowledge repository anytime, anywhere</p>
          </div>
        </div>
      </motion.section>

      {/* Testimonials */}
      <motion.section
        initial={{ opacity: 0 }}
        whileInView={{ opacity: 1 }}
        viewport={{ once: true }}
        transition={{ duration: 0.8 }}
        className="max-w-7xl mx-auto mb-16"
      >
        <h2 className="text-3xl font-bold text-center text-gray-900 mb-12">What Our Users Say</h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {[
            {
              quote: "This tool has transformed my research workflow. I save hours every week!",
              author: "Sarah K., Researcher"
            },
            {
              quote: "The AI summaries are surprisingly accurate and save me so much time.",
              author: "Michael T., Content Manager"
            },
            {
              quote: "Finally a tool that actually helps manage my growing list of bookmarks.",
              author: "Priya M., Software Developer"
            }
          ].map((testimonial, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: index * 0.2 }}
              className="bg-white p-6 rounded-xl shadow-lg"
            >
              <p className="text-gray-600 italic mb-4">"{testimonial.quote}"</p>
              <p className="font-medium text-indigo-600">{testimonial.author}</p>
            </motion.div>
          ))}
        </div>
      </motion.section>

      {/* CTA */}
      <motion.div
        initial={{ opacity: 0, scale: 0.9 }}
        whileInView={{ opacity: 1, scale: 1 }}
        viewport={{ once: true }}
        transition={{ duration: 0.5 }}
        className="max-w-2xl mx-auto text-center"
      >
        <h2 className="text-3xl font-bold text-gray-900 mb-6">Ready to Transform Your Productivity?</h2>
        <p className="text-xl text-gray-600 mb-8">
          Join thousands of professionals who are already saving time and staying organized.
        </p>
       <Link
  to="/signup"
  className="bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-3 px-8 rounded-full shadow-lg transform transition-transform hover:scale-105 duration-300 inline-block text-center"
>
  Get Started Now
</Link>
      </motion.div>
    </div>
  );
};

export default AboutPage;